postgresql:
  image: postgres:15.1-alpine3.16
  storage: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  env:
    POSTGRES_DB: sausage-store
    POSTGRES_USER: store
    POSTGRES_PASSWORD: storepassword
  containerPort: 5432
mongodb:
  image: mongo:7.0
  storage: 1Gi
  env:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: rootpassword
    MONGO_INITDB_DATABASE: sausage-store
  containerPort: 27017
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  # Настройки для базы данных отчетов
  reportsDb:
    name: sausage-store
    user: root
    password: rootpassword