global:
  imagePullPolicy: Always
annotations:
  path: /actuator/prometheus
  port: "8080"
  scrape: "true"
env:
  postgresUri: jdbc:postgresql://postgres:5432/sausage-store
  postgresUser: store
  postgresPassword: storepassword
  reportPath: /logs/reports
  logPath: /logs
service:
  port: 8080
revisionHistoryLimit: 15
replicas: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 2
image: urzhumtsev/sausage-backend:latest
imagePullPolicy: Always
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "250m"
containerPort: 8080
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 30
vpa:
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: "240m"
          memory: "0Mi"
        maxAllowed:
          cpu: "240m"
          memory: "500Mi"
        controlledResources: ["cpu", "memory"]