global:
  imagePullPolicy: Always
replicas: 1
revisionHistoryLimit: 15
strategy:
  type: Recreate
service:
  port: 80
ingress:
  host: front-urzhumtsev.2sem.students-projects.ru
  path: /
  pathType: Prefix
containerPort: 80
image: urzhumtsev/sausage-frontend:latest
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "1"
nginxConf: nginx.conf